### ISSUE TITLE
Webpack 4.0 Support

### ISSUE THREAD

**Issue by ccorcos** [lettertwo/appcache-webpack-plugin#23]
```
(node:42631) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
    at AppCachePlugin.apply (/Users/chet/Code/notion-next/node_modules/appcache-webpack-plugin/lib/index.js:100:16)
    at webpack (/Users/chet/Code/notion-next/node_modules/webpack/lib/webpack.js:37:12)
    at Object.<anonymous> (/Users/chet/Code/notion-next/src/cli/webpack.ts:39:19)
    at step (/Users/chet/Code/notion-next/src/cli/webpack.ts:32:23)
    at Object.next (/Users/chet/Code/notion-next/src/cli/webpack.ts:13:53)
    at /Users/chet/Code/notion-next/src/cli/webpack.ts:7:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/chet/Code/notion-next/src/cli/webpack.ts:3:12)
    at Object.build [as default] (/Users/chet/Code/notion-next/src/cli/webpack.ts:51:12)
    at Object.<anonymous> (/Users/chet/Code/notion-next/src/cli/client.ts:38:20)
```

**Comment by lettertwo** [comment]
Webpack 4 support is in as of [v1.4.0](https://www.npmjs.com/package/appcache-webpack-plugin/v/1.4.0)
